model: deepLOB_TF
modelKwargs: {}
numEpoch: 5
batchSize: 64
ticker: 
  - AAPL
steps:
  - TRAIN
  - TEST
maxFiles: 5
scaling: true
threshold: 'auto'
rowLim: 1000000
trainTestSplit: 0.9
lookForwardHorizon: 10
representation: 'orderbooks'
labelType: 'CATEGORICAL'